### ISSUE TITLE
链接预测的默认参数

### ISSUE THREAD

**Issue by KczCAF** [skepsun/adaptive_graph_diffusion_networks_with_hop-wise_attention#3]
请问您能给出README里面最优performance ogbl-ppa, ogbl-ddi, ogbl-citation2 对应的参数吗？
例如 python main.py --dataset ogbl-ddi --eval-metric hits --epochs .....
万分感激！

**Comment by skepsun** [comment]
所有的参数都在运行脚本里，比如ogbl-ddi对应的参数在`Adaptive-Graph-Diffusion-Networks/ogbl_no_sampling/scripts/ddi_agdn.sh`可以看到。

**Comment by KczCAF** [comment]
感谢！我找到了！
